# -*- coding: utf-8 -*-
"""Module Exam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mbLJX-j8QmqDwNnXOs_JFpmQlYKr96KW

Q2.
"""

def avg(*n):
  avg=sum(n)/len(n)
  print(avg)
avg(8,9,10,11)

"""Q5."""

class Maths:
  def Add(my,a,b):
    my.sum=a+b
    print(my.sum)
  def Div(my,a,b):
    my.div=a/b
    print(my.div)
  def Sub(my,a,b):
    my.sub=a-b
    print(my.sub)
  def Mul(my,a,b):
    my.mul=a*b
    print(my.mul)


f=Maths()
f.Add(5,6)
f.Div(6,7)
f.Sub(7,8)
f.Mul(8,9)

"""Q1."""

hrs=40
min=30
sec=hrs*3600+min*60
print(sec)

"""Q4."""

a=input('Enter number')
for i in a:
  if int(i)==1:
    print('One')
  elif int(i)==2:
    print('Two')
  elif int(i)==3:
    print('Three')
  elif int(i)==4:
    print('Four')
  elif int(i)==5:
    print('Five')
  elif int(i)==6:
    print('Six')
  elif int(i)==7:
    print('Seven')
  elif int(i)==8:
    print('Eight')
  elif int(i)==9:
    print('Nine')
  elif int(i)==0:
    print('Zero')

"""Q8."""

for i in range(1,8):
  if i==2 or i==4:
    continue
  for j in range(1,i+1):
    print(i,end='')
  print()

"""Q9."""

a='this is a test'
for i in range(len(a)):
  if i%2!=0:
    print(a[i],end='')

